1:
	gcc -Wall main.c -o main -lasound -lpthread
	#arm-linux-gcc -Wall main.c -o main -I ./Oplib/include/ -L ./Oplib/libObu/ -lasound -lpthread
2:
	arm-linux-gnueabihf-gcc -Wall main.c -o main -I ./Oplib/include/ -L ./Oplib/libObu/ -lasound -lpthread

clean:
	rm main
	rm *.bak
