CC = D:/qnx660/host/win32/x86/usr/bin/ntoarmv7-gcc.exe
TARGET = taskmonitor
all:
	$(CC) taskmonitor.c -o $(TARGET)
	$(CC) taskmonitorTest.c -o taskmonitorTest
clean:
	rm $(TARGET)
	rm taskmonitorTest