CC = D:/mmgz.QNX_KERNEL/qnx660/host/win32/x86/usr/bin/ntoarmv7-gcc.exe

all:
	$(CC) processRcv.c -o processRcv
	$(CC) processSend.c -o processSend
	$(CC) processClear.c -o processClear
	
clean:
	rm processRcv
	rm processSend
	rm processClear